name: Linting

on:
  push:
    branches:
      - "*"

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies and build package
        run: |
          poetry install

      - name: Run pre-push script
        run: poetry run python pre_push.py
